apiVersion: v2
appVersion: 1.15.3
description: Kubescape is an E2E Kubernetes cluster security platform
home: https://www.armosec.io/
maintainers:
- email: ben@armosec.io
  name: Ben Hirschberg
  url: https://www.linkedin.com/in/benyamin-ben-hirschberg-66141890
- email: dw@armosec.io
  name: David Wertenteil
  url: https://www.linkedin.com/in/david-wertenteil-0ba277b9
- email: bez@armosec.io
  name: Bezalel Brandwine
  url: https://www.linkedin.com/in/bezalel-brandwine
- email: mshkalim@armosec.io
  name: Matan Shkalim
  url: https://www.linkedin.com/in/matan-shkalim
name: kubescape-operator
type: application
version: 1.15.3
